Add windows tests

diff --git a/.github/workflows/gha.yml b/.github/workflows/gha.yml
--- a/.github/workflows/gha.yml
+++ b/.github/workflows/gha.yml
@@ -84,3 +84,30 @@ jobs:
        - name: Create ZIP archive
          if: steps.cache-pmdk.outputs.cache-hit != 'true'
          run: utils/CREATE-ZIP.ps1 -b ${{ matrix.CONFIG }}
+
+       - name: Run tests
+         if: steps.cache-pmdk.outputs.cache-hit == 'true'
+         shell: powershell
+         run: |
+           if ($true) {
+               cd src\test
+               echo "`$Env:NON_PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
+               echo "`$Env:PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
+               echo "`$Env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
+               echo "`$Env:PMDK_NO_ABORT_MSG = `"1`"" >> testconfig.ps1
+               echo "`$Env:TM = `"1`"" >> testconfig.ps1
+               write-output "config = {'unittest_log_level': 1, 'pmem_fs_dir': 'C:\\temp', 'non_pmem_fs_dir': 'C:\\temp', 'tm': True, 'test_type': 'check', 'fs': 'all', 'fs_dir_force_pmem': 1, 'keep_going': False, 'timeout': '4m', 'build': 'debug', 'force_enable': None}" | out-file "testconfig.py" -encoding utf8
+
+               if ("${{ matrix.CONFIG }}" -eq "Debug") {
+                   ./RUNTESTS.ps1 -b debug -o 4m
+                   if ($?) {
+                       ./RUNTESTS.py -b debug
+                   }
+               }
+               if ("${{ matrix.CONFIG }}" -eq "Release") {
+                   ./RUNTESTS.ps1 -b nondebug -o 4m
+                   if ($?) {
+                       ./RUNTESTS.py -b release
+                   }
+               }
+           }
